### ISSUE TITLE
Why Test Input Size of self-distillation phase is 1024*2048? instead of 512*1024 as before?

### ISSUE THREAD

**Issue by nbilx** [JDAI-CV/FADA#11]
@wyvernbai @krumo Firstly, thanks a lot for your great work. However, I have a question about the test input size when evaluating the self-distillation model. Because I have seen that you set INPUT_SIZE_TEST: (2048, 1024) in the fille configs/deeplabv2_r101_tgt_self_distill.yaml. 

I am a little confused because when evaluating other models, the INPUT_SIZE_TEST is (1024, 512). Why do you change it to (2048, 1024) when evaluating the self-distillation model? In my opinion, it may cause unfair comparison, since intuitively the larger the input size is, the better the performance will be. Also, as I know, most previous works use (1024,512) as the test input size.

Do I miss something? Thanks a lot. Looking forward to your reply!

**Comment by krumo** [comment]
Hi, thanks for your question!
As stated in the paper, for self-distillation model, we explored different tricks to boost the performance hoping to gain the insight about which kind of tricks are orthogonal to our method. We utilize a large resolution because we find it does help increase our performance. Previous works like [Tsai et al. 2019](https://arxiv.org/pdf/1901.05427.pdf) also explore existing methods compatible with their approach. And as I mentioned in #5 , some tricks work for supervised learning without domain shift don't always work under domain adaptation settings. A larger resolution also fails to benefit all compared domain adaptation methods.

**Comment by Hectoor** [comment]
> @wyvernbai @krumo Firstly, thanks a lot for your great work. However, I have a question about the test input size when evaluating the self-distillation model. Because I have seen that you set INPUT_SIZE_TEST: (2048, 1024) in the fille configs/deeplabv2_r101_tgt_self_distill.yaml.
> 
> I am a little confused because when evaluating other models, the INPUT_SIZE_TEST is (1024, 512). Why do you change it to (2048, 1024) when evaluating the self-distillation model? In my opinion, it may cause unfair comparison, since intuitively the larger the input size is, the better the performance will be. Also, as I know, most previous works use (1024,512) as the test input size.
> 
> Do I miss something? Thanks a lot. Looking forward to your reply!

I reproduce the FADA method, and the MIoU is 46 with INPUT_SIZE_TEST 1024x512 when the MIoU is 49 with INPUT_SIZE_TEST 2048x1024.
