### ISSUE TITLE
Problems when you save soft labels for self distill 

### ISSUE THREAD

**Issue by taintpro98** [JDAI-CV/FADA#15]
Process of saving soft labels happen in test.py

mask = get_color_pallete(pred, "city")
mask_filename = name[0] if len(name[0].split("/"))<2 else name[0].split("/")[1]
mask.save(os.path.join(output_folder, mask_filename))

You saved them as PIL images with colors(If I understand right)

But when you loaded them in cityscapes_self_distill.py 

label = np.array(Image.open(datafile["label"]),dtype=np.float32)

Then, you added ignore label 

label_copy = self.ignore_label * np.ones(label.shape, dtype=np.float32)
for k, v in self.id_to_trainid.items():
        label_copy[label == k] = v
# for k in self.trainid2name.keys():
#     label_copy[label == k] = k
label = Image.fromarray(label_copy)

I think the images you loaded is not in the format with label id but color code 

Please show me where I'm wrong, thanks.

**Comment by krumo** [comment]
Hi, thanks for your interest!
As you could see [here](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/core/utils/misc.py#L68), we convert the image into 'P' mode instead of color mode. For the mechanism of 'P' mode I would refer to [this post](https://stackoverflow.com/questions/52307290/what-is-the-difference-between-images-in-p-and-l-mode-in-pil) at stackoverflow. Thus, when you load soft labels from saved images, they would be loaded in the format of label id.

**Comment by taintpro98** [comment]
thanks for your answer. It's very helpful
